# Generated by Django 4.2.10 on 2024-03-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_user_cart_cart_id_cartitem_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
