# Generated by Django 4.2.10 on 2024-04-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_is_returned_order_return_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_returned',
            field=models.CharField(choices=[('Not returned', 'Not returned'), ('Processing', 'Processing'), ('Returned', 'Returned')], default='Not returned', max_length=20),
        ),
    ]
