# Generated by Django 4.2.10 on 2024-04-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_order_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_returned',
            field=models.CharField(choices=[('NOT_RETURNED', 'Not returned'), ('PROCESSING', 'Processing'), ('RETURNED', 'Returned')], default='NOT_RETURNED', max_length=20),
        ),
    ]
