# Generated by Django 4.2.10 on 2024-04-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_order_coupon_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_without_discount',
            field=models.IntegerField(default=0),
        ),
    ]
