# Generated by Django 4.2.10 on 2024-04-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_order_price_without_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_discounted',
            field=models.IntegerField(default=0),
        ),
    ]
