# Generated by Django 4.2.10 on 2024-05-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_order_payment_status_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH_ON_DELIVERY', 'Cash on Delivery'), ('WALLET', 'Wallet'), ('RAZORPAY', 'Razorpay')], default='CASH_ON_DELIVERY', max_length=20),
        ),
    ]
