# Generated by Django 4.2.10 on 2024-03-10 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x03D53A48>', max_length=200),
        ),
    ]
