# Generated by Django 4.2.10 on 2024-03-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_address_alter_profile_uid_account_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alt_phone_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='ph_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(default='<function uuid4 at 0x04403A48>', max_length=200),
        ),
    ]
