# Generated by Django 4.2.10 on 2024-03-04 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_product_productimage_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_id',
            new_name='product',
        ),
    ]
