# Generated by Django 4.2.10 on 2024-03-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_size_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='size',
        ),
    ]
