# Generated by Django 4.2.10 on 2024-03-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_productvariation_delete_productvariantstock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
