# Generated by Django 4.2.10 on 2024-04-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_average_rating_product_popularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='promotion_price',
        ),
        migrations.AddField(
            model_name='product',
            name='regular_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
