# Generated by Django 4.2.10 on 2024-04-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='variant',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
